# Generated by Django 4.1.3 on 2022-11-28 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='Order of advice')),
                ('description', models.CharField(help_text='Enter flag descr', max_length=150)),
                ('showtime', models.DateTimeField(help_text='Time to show')),
                ('penalty', models.IntegerField(help_text='Penalty for advice')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlagType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Enter flag descr', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdvice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('showed', models.BooleanField(default=False, help_text='Has showed')),
                ('notneed', models.BooleanField(default=False, help_text='Not need advice')),
                ('take_time', models.DateTimeField(help_text='Time of taking advice')),
                ('advice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnir.advice')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hash', models.BigIntegerField(help_text='Enter flag hash')),
                ('captured', models.BooleanField(default=False, help_text='Flag is captured')),
                ('capture_time', models.DateTimeField(help_text='Time of capture')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnir.flagtype')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
