# Generated by Django 4.1.3 on 2022-11-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='description',
            field=models.CharField(help_text='Enter flag descr', max_length=500),
        ),
    ]
