# Generated by Django 4.1.3 on 2022-11-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnir', '0003_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='flagsubmit',
            field=models.IntegerField(default=0),
        ),
    ]
